# Hız ayarları
UP add speed 0.25
DOWN add speed -0.25

# CTRL+0: Shaderları Temizle
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "Shaderlar Kapatıldı"

# CTRL+1: Monster Kurtarma Paketi (Yolları kısalttım, daha stabil)
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl"; show-text "Anime4K: Mod Active"

# CTRL+2: ArtCNN (Zaten sendeki çalışan buydu muhtemelen)
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F16.glsl:~~/shaders/adaptive-sharpen.glsl"; show-text "ArtCNN + Sharpen"
